package org.developers.api.response.YouTube;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class YouTubeSubtitle {
    private String id;
    private String videoId;
    private String language;
    private String languageCode;
    private String name;
    private String content;
    private String lastUpdated;
    private boolean isAutoGenerated;
    private boolean isTranslated;
    private String sourceLanguage;
    private String sourceLanguageCode;
} 